KO_YEAR_SUMMARY_DATA = "/static/ko/summaryData/year_result.csv"
KO_QUARTER_SUMMARY_DATA = "/static/ko/summaryData/quarter_result.csv"
KO_YEAR_BS_DATA = "/static/ko/fsData/bs_year_result.csv"
KO_QUARTER_BS_DATA = "/static/ko/fsData/bs_quarter_result.csv"
KO_YEAR_CF_DATA = "/static/ko/fsData/cf_year_result.csv"
KO_QUARTER_CF_DATA = "/static/ko/fsData/cf_quarter_result.csv"
KO_YEAR_PL_DATA = "/static/ko/fsData/pl_year_result.csv"
KO_QUARTER_PL_DATA = "/static/ko/fsData/pl_quarter_result.csv"

US_YEAR_SUMMARY_DATA = "/static/us/rawData/year_result.csv"
US_QUARTER_SUMMARY_DATA = "/static/us/rawData/quarter_result.csv"
US_YEAR_BS_DATA = "/static/us/fsData/bs_year_result.csv"
US_QUARTER_BS_DATA = "/static/us/fsData/bs_quarter_result.csv"
US_YEAR_CF_DATA = "/static/us/fsData/cf_year_result.csv"
US_QUARTER_CF_DATA = "/static/us/fsData/cf_quarter_result.csv"
US_YEAR_PL_DATA = "/static/us/fsData/pl_year_result.csv"
US_QUARTER_PL_DATA = "/static/us/fsData/pl_quarter_result.csv"
